this file only for translate language from database
<span>{{__('inactive')}}</span>
<span>{{__('Contain')}}</span>
<span>{{__('media')}}</span>
<span>{{__('list')}}</span>
<span>{{__('template')}}</span>
<span>{{__('button')}}</span>
<span>{{__('text')}}</span>
<span>{{__('admin')}}</span>
<span>{{__('user')}}</span>
<span>{{__('Disconnect')}}</span>
<span>{{__('lifetime')}}</span>
<span>{{__('trial')}}</span>
<span>{{__('Open')}}</span>
<span>{{__('Closed')}}</span>
<span>{{__('validation.accepted')}}</span>
<span>{{__('validation.accepted_if')}}</span>
<span>{{__('validation.active_url')}}</span>
<span>{{__('validation.after')}}</span>
<span>{{__('validation.after_or_equal')}}</span>
<span>{{__('validation.alpha')}}</span>
<span>{{__('validation.alpha_dash')}}</span>
<span>{{__('validation.alpha_num')}}</span>
<span>{{__('validation.array')}}</span>
<span>{{__('validation.before')}}</span>
<span>{{__('validation.before_or_equal')}}</span>
<span>{{__('validation.between.numeric')}}</span>
<span>{{__('validation.between.file')}}</span>
<span>{{__('validation.between.string')}}</span>
<span>{{__('validation.between.array')}}</span>
<span>{{__('validation.boolean')}}</span>
<span>{{__('validation.confirmed')}}</span>
<span>{{__('validation.current_password')}}</span>
<span>{{__('validation.date')}}</span>
<span>{{__('validation.date_equals')}}</span>
<span>{{__('validation.date_format')}}</span>
<span>{{__('validation.declined')}}</span>
<span>{{__('validation.declined_if')}}</span>
<span>{{__('validation.different')}}</span>
<span>{{__('validation.digits')}}</span>
<span>{{__('validation.digits_between')}}</span>
<span>{{__('validation.dimensions')}}</span>
<span>{{__('validation.distinct')}}</span>
<span>{{__('validation.email')}}</span>
<span>{{__('validation.ends_with')}}</span>
<span>{{__('validation.enum')}}</span>
<span>{{__('validation.exists')}}</span>
<span>{{__('validation.file')}}</span>
<span>{{__('validation.filled')}}</span>
<span>{{__('validation.gt.numeric')}}</span>
<span>{{__('validation.gt.file')}}</span>
<span>{{__('validation.gt.string')}}</span>
<span>{{__('validation.gt.array')}}</span>
<span>{{__('validation.gte.numeric')}}</span>
<span>{{__('validation.gte.file')}}</span>
<span>{{__('validation.gte.string')}}</span>
<span>{{__('validation.gte.array')}}</span>
<span>{{__('validation.image')}}</span>
<span>{{__('validation.in')}}</span>
<span>{{__('validation.in_array')}}</span>
<span>{{__('validation.integer')}}</span>
<span>{{__('validation.ip')}}</span>
<span>{{__('validation.ipv4')}}</span>
<span>{{__('validation.ipv6')}}</span>
<span>{{__('validation.json')}}</span>
<span>{{__('validation.lt.numeric')}}</span>
<span>{{__('validation.lt.file')}}</span>
<span>{{__('validation.lt.string')}}</span>
<span>{{__('validation.lt.array')}}</span>
<span>{{__('validation.lte.numeric')}}</span>
<span>{{__('validation.lte.file')}}</span>
<span>{{__('validation.lte.string')}}</span>
<span>{{__('validation.lte.array')}}</span>
<span>{{__('validation.mac_address')}}</span>
<span>{{__('validation.max.numeric')}}</span>
<span>{{__('validation.max.file')}}</span>
<span>{{__('validation.max.string')}}</span>
<span>{{__('validation.max.array')}}</span>
<span>{{__('validation.mimes')}}</span>
<span>{{__('validation.mimetypes')}}</span>
<span>{{__('validation.min.numeric')}}</span>
<span>{{__('validation.min.file')}}</span>
<span>{{__('validation.min.string')}}</span>
<span>{{__('validation.min.array')}}</span>
<span>{{__('validation.multiple_of')}}</span>
<span>{{__('validation.not_in')}}</span>
<span>{{__('validation.not_regex')}}</span>
<span>{{__('validation.numeric')}}</span>
<span>{{__('validation.password')}}</span>
<span>{{__('validation.present')}}</span>
<span>{{__('validation.prohibited')}}</span>
<span>{{__('validation.prohibited_if')}}</span>
<span>{{__('validation.prohibited_unless')}}</span>
<span>{{__('validation.prohibits')}}</span>
<span>{{__('validation.regex')}}</span>
<span>{{__('validation.required')}}</span>
<span>{{__('validation.required_array_keys')}}</span>
<span>{{__('validation.required_if')}}</span>
<span>{{__('validation.required_unless')}}</span>
<span>{{__('validation.required_with')}}</span>
<span>{{__('validation.required_with_all')}}</span>
<span>{{__('validation.required_without')}}</span>
<span>{{__('validation.required_without_all')}}</span>
<span>{{__('validation.same')}}</span>
<span>{{__('validation.size.numeric')}}</span>
<span>{{__('validation.size.file')}}</span>
<span>{{__('validation.size.string')}}</span>
<span>{{__('validation.size.array')}}</span>
<span>{{__('validation.starts_with')}}</span>
<span>{{__('validation.string')}}</span>
<span>{{__('validation.timezone')}}</span>
<span>{{__('validation.unique')}}</span>
<span>{{__('validation.uploaded')}}</span>
<span>{{__('validation.url')}}</span>
<span>{{__('validation.uuid')}}</span>